### ISSUE TITLE
Fix 'total returned features' logged value

### ISSUE THREAD

**Issue by abiddiscombe-os** [OrdnanceSurvey/osdatahub-js#28]
For queries that complete fully (total number of features is under the feature return limit), the total number of returned features appears to be incorrect (lower than expected). This could be due to either:

1. The incorrect variable being passed as the final feature count,
2. Failure to run the log command before the final page of results has been added to the temporary accumulated response object.

**Comment by JEPooley** [comment]
Fixed ready for next release
